Repository Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding, pull requests merged in 2021-05, with the labels that each got.

#4 brand_as_default
  deployment/kubernetes/values.yaml.dist
Labels: enhancement

#6 chore: 🍰 Replace Ocelot Logos 619x593 With 600x570
  .gitignore
  branding/static/img/custom/password-reset.svg
  branding/static/img/custom/welcome.svg
Labels: devOps

#8 chore: 🍰 Implement Use Of package.json 'Version' Etc. For Build And Refine Helm Chart
  .github/workflows/publish.yml
  deployment/kubernetes/Chart.yaml
  deployment/kubernetes/README.md
  deployment/kubernetes/dns.values.template.yaml
  deployment/kubernetes/nginx.values.template.yaml
  deployment/kubernetes/values.template.yaml
  docker/backend.Dockerfile
  docker/maintenance.Dockerfile
  docker/neo4j.Dockerfile
  docker/webapp.Dockerfile
  package.json
Labels: devOps

#11 🛠 [Refactor] Add README And LICENSE
  LICENSE.md
  README.md
Labels: devOps, documentation

#12 💥 Release v1.0.3
  branding/constants/links.js
  branding/constants/logos.js
  branding/constants/metadata.js
  branding/static/img/custom/Logo-Horizontal-Dark.svg
  branding/static/img/custom/logo-horizontal.svg
  branding/static/img/custom/logo-squared.svg
  branding/static/img/custom/password-reset.svg
  branding/static/img/custom/sign-up.svg
  branding/static/img/custom/under-maintenance.svg
  branding/static/img/custom/welcome.svg
  docker/backend.Dockerfile
  docker/maintenance.Dockerfile
  docker/neo4j.Dockerfile
  docker/webapp.Dockerfile
  package.json
Labels: devOps, enhancement
